---
title: "Eksamensopgave 1"
author: "Andreas Methling"
date: "6 sep 2021"
output: pdf_document
---

#Opgave 1

##1. Explain crucial differences between the Solow model and the Ramsey, Cass and Koopman model. Does it affect the overall conclusions?

##2.  Piketty (2014) argues that a fall in the growth rate of the economy is likely to an increase in the difference between the real interest rate and the growth rate. This problem asks you to investigate this issue in the context of the Ramsey Cass Koopmans model. Specially, consider a Ramsey Cass Koopmans economy that is on its balanced growth path, and suppose there is a permanent fall in g.

##2.1  How, if at all, does this affect the $\dot k$ = 0 curve?
Et fald i g vil paavirke $\dot k = 0$ igennem sidste led i nedenstaaende funktion:
$$\dot k(t) = f(k(t)) -c(t) - (n+g)k(t)$$ 

Sidste led $-(n+g)k(t)$ vil blive stoerre naar $g$ falder, hvilket vil resultere i, at det midterste led$-c(t)$ ogsaa bliver noedt til at blive stoerre for at $\dot k$ bliver ved med at vaere = 0. Dette betyder, at kurven for $\dot k$ bliver hoejere for da der skal en hoejere $c$ til for at $\dot k$ forbliver 0. Ligeledes bliver kurven bredere da $f'(k) = n + g$ vil blive mindre, da k stiger, fordi vi er langt ude paa kurven.
For at holde kapitalapparatet stabilt skal man altsaa bruge faerre investeringer, derfor stiger $c(t)$

##2.2 How, if at all, does this affect the $\dot c$ = 0 curve?
Det kan ses udfra udtrykket $$\frac{\dot c(t)}{c(t)} = \frac{f'(k(t))-\rho-\theta g}{\theta}$$
Hvor taelleren skal vaere 0, hvilket omskrevet giver $f'(k) = \rho+g$
Et fald i $g$ vil medfoerer et fald i $f'(k)$ og da vi antager aftagende marginalprodukt, saa betyder det, at vi er langt ude paa af k, hvilket medfoerer, at givet en vilkaarlig c vaerdi vil der skulle bruges en stoerre K, hvilket betyder at C linjen skal skubes til hoejre.

##2.3 At the time of the change, does c rise, fall, or stay the same, or is it not possible to tell?

Det kan vi ikke sige noget om, for vi rykker begge baade kurven og linjen og vi aner ikke hvor vi kommer til at starte, det kommer an paa hvor meget man rykker dem paa tegningen. Alt andet lige kommer det nye start punkt til at vaere under $\dot k$ kurven og til venstre for $\dot c$ linjen.

##2.4 At the time of the change, does r g rise, fall, or stay the same, or is it not possible to tell?
Husholdningerne ved ikke at der kommer et stoed, det er derved et uventet stoed og de har ikke maksimeret historisk for det, hvilket vil sige, at K ikke aendre sig, da det er historisk opbygget. Da K ikke aendre sig, saa aendre $f'(k)$ sig heller ikke, og da $f'(k) = r$, saa aendre r sig heller ikke, hvilket vil sige, at kun g aendre sig. Afstanden bliver derved stoerre i mellem de to, da g falder imens r forbliver det samme.

##2.5 In the long run, does r g rise, fall, or stay the same, or is it not possible to tell? 

Find et ud tryk hvor vi skal finde diff af 

er theta stoerre ligmed eller mindre end 1

#Opgave 2

Consider the following overlapping generations framework. Welfare is equal to:

$$U_t = u(C_{1t} + \beta u(C_{2t+1}$$ with $\beta = \frac{1}{1+\rho}$ the discount factor.

Assume the utility function is logarithmic:
$$u(C_{jt} = lnC_{jt}$$

We will assume that the government implements a pension scheme, more specifically, a pay-as-you-go social security scheme, where the government taxes each young individual by an amount T , and uses that amount to pay benefits to old individuals. Hence, the budget constraints is given by:

$$C_{1t}+S_t = w - T$$

whereas period 2 consumption is givien by:
$$C_{2t+1} = S_t(1+r) + (1+n)T$$

Note that $n$ represents population growth. Take the wage $w$ and interest rate $r$ as exogenous and solve the following:

##Set up the intertemporal maximazation problem and derive the EUler equation:

##Derive $S_t$ as a function of $r$, $w$ and $T$. How does an increase in $T$ affect savings (show mathematically)? Discuss the result.