---
title: "4. makro part 1"
author: "Andreas Methling"
date: "4/11/2021"
output: pdf_document
---

# Post Keynesian theory

## Opgave 2: Explain the following statement using Kalecki’s micro-foundations: "But pay can rise for a variety of reasons, some more benign than others. For a given level of productivity, higher wages must show up in one of two ways: as higher inflation or as a higher "labour share" of GDP". Why is it that, if nominal wages increase and firms choose not to pass on the higher labour costs to prices, the "labour share" increases?

For et given niveau af $u$ kan der i modellen kun komme højere lønninger ved højere inflation, hvilket vil sige en stigning i $P = (1+\tau)W\alpha0$ eller ved en stigning i lønandel af BNP givet ved $\tau$ i $\pi = \frac{\tau}{1+\tau}$, hvor lønandel er $1-\pi$. 

given $P = (1+\tau)W\alpha0$ and $\frac{1}{\alpha0}$ is given the mark-up has to fall, then $\pi$ falls and the wage share increases.

## Opgave 3: Assume that the increase in nominal wages discussed in the note is finally passed on to prices one-on-one. What would be the impact on output (proxied by the rate of capacity utilization and growth. Use the graphical setting developed in the Kalecki-Steindl model.

If the increase in the nominal wage is passed on to prices one-to-one, then the real wage would be unchanged, which means that the capacity utilization and growth also would be unchanged.


## Opgave 4: Evaluate the following statement through the lenses of the Kalecki-Steindl graphical device: "But an ever-rising labour share would be a worry: it would crimp companies' profits and thus the investments that are crucial to improving long-run economic growth". Does an increase in the labour share reduce long-run growth in this model? Why? Why not?

In the Kalecki-Steindl model an increase in the labour share $1-\pi$ does not reduced growth. On the contrary, it increases demand and growth. To see this graphically note that the reduction of $\pi$ changed the slope of $g$, which rotates $g$ downwards an thereby creating a higher eqilibrium for investment, long run growth capacity utilization the rate of profit and the real wage. There is no tension between the compensation of labour (the real wage) and capital(the rate of profit) because the level of income has increased as denoted by the outward movement of the wage-profit line (u*). In other words even if distribution is now more favourable for workers, this does not come at the expense of firms' absolute level of income. This would only happen if income cannot be increased, which only occurs when the rate of u is at its maximum level u = 1.

In short the firms take a smaller part of the pie, but the pie is bigger, so they get more in absolute value. SO in the end, what matter? the relative level or the total share in absolute value?

## Opgave 5:  The note stresses that: "There is another, happier, possibility. If productivity rises, then wage growth need not cause sustained inflation, nor push up the labour share. Instead the economic pie would grow, with more for everyone."


### a) Explain why a raise in productivity could offset the inflationary pressure or increasing wages.

Given $P = (1+\tau)W\alpha0$, an increase in productivity is represented by a decrease in the unit labour requirement $a0$ i.e. it becomes possible to produce more with the same amount of workers. in a context of rising wages as the one described in the note, a fall in a0 could offset the upward pressure on prices, thereby leaving them constant (the overall effect on prices would ultimately depend on the relative changes of $W$ and $a0$.)

A rise in wages in this model is always expansionary, this can be because of the structure i.e. a closed economy.


### b) Illustrate this scenario using the Kalecki-Steindl graphical model. Does the model predict a higher size of the income (a.k.a. "the economic pie")? What would be needed for the "economic pie" to grow in the model?

In order to illustrate the scenario you ahve to bear in mind the labour productitivty is one of the determinants of the equilibrium real wage. A higher productivity (lower a0) increased the equillibrium real wage. However since a0 is not a determinat of the equlibrium level of the rate of profit, the rate of capacatiy utilization and the rate of growth alle the three reamin unchanged. The reason why there are no cahnges in outout and growrth is that in PK theiry theses variables are demand determmined, and the shcok on a0 is a supply-side shock. SO, the increase in productivity leads to higher wages and a lower level of employment, leaving total workers' disposable income unchanged. Con sumption and output are therefor constant.

Increase realwage on the graph without changing any other levels, can be hard.

# SFC
## Opgave 1:  Explain crucial differences between Post-Keynesian SFC-models and General Equilibrium models?

DSGE-models is born of the New Neoclassic Synthesis which implies Rationalizes expectations, inter temporal optimizing, imperfect competition, and price inertia. SFC models are older models with keynesian behavioral relations, national accounting identities and single equation estimations. Furthermore DSGE models have recieved critics in the form of that the finacial sector only plays the role of distributing credit not as a cause of instability. Financial flows also didnt play any role or a small one and privat debt played no role. All these three critics can be looked at in an SFC framework.

## Opgave 2: Explain some of the key transmission channels between financial markets and the real economy - how does a drop in the price of a financial asset affect the realeconomy?


## Opgave 3:  Discuss the macroeconomic effects of a drop in house prices within the empirical SFC-model.



## Opgave 4: Does the high level of household debt pose a risk to macroeconomic stability in case of a negative shock to the Danish Economy?


# MMT

## Opgave 1: Why would a Central Bank normally refrain from setting the policy rate significantly below 0%?


## Opgave 2: Can Central Banks keep on pursuing an expansionary monetary policy when the zero-lower bound has been hit? If so, how can they do it?


## Opgave 3: Why is it that quantitative easing does not necessarily lead to an increase in lending?


## Opgave 4: Taking into account Epstein’s concerns about the international spillovers of expansionary monetary policies, what are the risks of sustaining quantitative easing for an extended period? What might be the reasons why despite these risks, Central Banks these days (end of 2021) are being slow at tapering quantitative easing?




